### PR TITLE
Feature/trello 108 pattern steps

### PR DESCRIPTION
**Pull request by kiddhustle**
added to pattern library:

* steps
* steps on grid

### CODE REVIEW

**Comment by appility** [comment]
Actually - I've just noticed the header seems to be breaking when I view the deployed version

**Comment by dahfool** [comment]
@appility @kiddhustle seems like new version of bourbon is breaking old components e,g header and footer.

**Comment by kiddhustle** [comment]
oh yea I think I will just remove the header and footer for the library for now as it is due to change.

if anyone wants the use the old header they will have to checkout v.0.1.3, no one is actually going to be using the any version beyond this in production

Version 1.0.0 will be when we are production ready

**Comment by kiddhustle** [comment]
Michal has had an initial look at the steps patterns and seems happy with it but he won't be able to fully review until after today (he's currently working on the prototype)

**Comment by kiddhustle** [comment]
Michal has requested these changes which will be in the next commit:

- [x] equal spacing between text boxes (30px)
- [x] steps arrow reduce width
- [x] steps arrow resize
- [x] full width (past page gutter)
- [x] change button highlight colour
- [x] change colour of tabswitcher to bg white

**Pull request merged**
