### PR TITLE
(fix) adding dark red hover to red button, adding auto width to mobil…

### PR DESCRIPTION
**Pull request by appility**
…e toggle menu button

### CODE REVIEW

**Comment by appility** [comment]
it's set to merge into develop now

**Comment by kiddhustle** [comment]
this hasn't been merged into develop has it?

**Comment by dahfool** [comment]
@appility @kiddhustle it hasn't been merged, there seems to be some conflicts.

**Comment by appility** [comment]
adding to old-styleguide instead

**Pull request closed without merging**
